version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:7.4.2
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 1
    volumes: 
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/redis:/data
    networks:
      - web-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm run start:prod:api
    environment:
      - REDIS_HOST=redis
    env_file: 
      - path: ./.env
        required: false
    restart: always
    ports:
      - 3000:3000
    networks:
      - web-network
    depends_on:
      - redis

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm run start:prod:worker
    environment:
      - REDIS_HOST=redis
    env_file: 
      - path: ./.env
        required: false
    restart: always
    networks:
      - web-network
    depends_on:
      - redis

networks:
  web-network:
